deploy:
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - VERSION
  before_script:
    - apk add --no-cache curl bash
    - curl -LO https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/oc/latest/linux/oc.tar.gz
    - tar -xf oc.tar.gz && mv oc /usr/local/bin/
    - echo "$CERN_REGISTRY_TOKEN" | docker login registry.cern.ch -u ravinab --password-stdin
    - oc login --server=https://api.paas.okd.cern.ch --token="$OC_TOKEN"
  script:
    - bash deploy.sh v2.24.0
  environment:
    name: production
    url: https://itopcptoolkit.web.cern.ch