# Block tree derived from ConfigFactory.py
# Each entry maps a YAML top-level key to its Python class/function,
# its sub-blocks, and whether it can appear multiple times (list in YAML).

BLOCK_TREE = [
    # ── Core ────────────────────────────────────────────────────────────────
    {
        "name": "CommonServices",
        "label": "Common Services",
        "group": "Core",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.CommonServicesConfig",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "PileupReweighting",
        "label": "Pileup Reweighting",
        "group": "Core",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PileupReweightingBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "EventCleaning",
        "label": "Event Cleaning",
        "group": "Core",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.EventCleaningConfig.EventCleaningBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "GeneratorLevelAnalysis",
        "label": "Generator Level Analysis",
        "group": "Core",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.GeneratorAnalysisBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "Bootstraps",
        "label": "Bootstraps",
        "group": "Core",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.BootstrapGeneratorConfig.BootstrapGeneratorConfig",
        "is_function": False,
        "sub_blocks": [],
    },
    # ── Objects ─────────────────────────────────────────────────────────────
    {
        "name": "Jets",
        "label": "Jets",
        "group": "Objects",
        "repeatable": True,
        "class_path": "JetAnalysisAlgorithms.JetAnalysisConfig.makeJetAnalysisConfig",
        "is_function": True,
        "sub_blocks": [
            {
                "name": "JVT",
                "label": "JVT",
                "repeatable": False,
                "class_path": "JetAnalysisAlgorithms.JetJvtAnalysisConfig.JetJvtAnalysisConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "BJetCalib",
                "label": "B-Jet Calibration",
                "repeatable": False,
                "class_path": "JetAnalysisAlgorithms.BJetCalibAnalysisConfig.BJetCalibAnalysisConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "Uncertainties",
                "label": "Jet Uncertainties",
                "repeatable": False,
                "class_path": "JetAnalysisAlgorithms.JetUncertaintiesConfig.JetUncertaintiesConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "FlavourTagging",
                "label": "Flavour Tagging",
                "repeatable": True,
                "class_path": "FTagAnalysisAlgorithms.FTagAnalysisConfig.FTagConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "FlavourTaggingEventSF",
                "label": "Flavour Tagging Event SF",
                "repeatable": True,
                "class_path": "FTagAnalysisAlgorithms.FTagSFAnalysisConfig.FTagEventSFBlock",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "XbbTagging",
                "label": "Xbb Tagging",
                "repeatable": False,
                "class_path": "FTagAnalysisAlgorithms.XbbAnalysisConfig.XbbConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "PtEtaSelection",
                "label": "pT/η Selection",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PtEtaSelectionBlock",
                "is_function": False,
                "sub_blocks": [],
            },
        ],
    },
    {
        "name": "Electrons",
        "label": "Electrons",
        "group": "Objects",
        "repeatable": True,
        "class_path": "EgammaAnalysisAlgorithms.ElectronAnalysisConfig.ElectronCalibrationConfig",
        "is_function": False,
        "sub_blocks": [
            {
                "name": "WorkingPoint",
                "label": "Working Point",
                "repeatable": True,
                "class_path": "EgammaAnalysisAlgorithms.ElectronAnalysisConfig.ElectronWorkingPointSelectionConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "IFFClassification",
                "label": "IFF Classification",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.IFFLeptonDecorationBlock",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "PtEtaSelection",
                "label": "pT/η Selection",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PtEtaSelectionBlock",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "TriggerSF",
                "label": "Trigger SF",
                "repeatable": False,
                "class_path": "EgammaAnalysisAlgorithms.ElectronAnalysisConfig.ElectronTriggerAnalysisSFBlock",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "LRTMerging",
                "label": "LRT Merging",
                "repeatable": False,
                "class_path": "EgammaAnalysisAlgorithms.ElectronAnalysisConfig.ElectronLRTMergedConfig",
                "is_function": False,
                "sub_blocks": [],
            },
        ],
    },
    {
        "name": "Muons",
        "label": "Muons",
        "group": "Objects",
        "repeatable": True,
        "class_path": "MuonAnalysisAlgorithms.MuonAnalysisConfig.MuonCalibrationConfig",
        "is_function": False,
        "sub_blocks": [
            {
                "name": "WorkingPoint",
                "label": "Working Point",
                "repeatable": True,
                "class_path": "MuonAnalysisAlgorithms.MuonAnalysisConfig.MuonWorkingPointSelectionConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "TriggerSF",
                "label": "Trigger SF",
                "repeatable": False,
                "class_path": "MuonAnalysisAlgorithms.MuonAnalysisConfig.MuonTriggerAnalysisSFBlock",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "LRTMerging",
                "label": "LRT Merging",
                "repeatable": False,
                "class_path": "MuonAnalysisAlgorithms.MuonAnalysisConfig.MuonLRTMergedConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "ContainerMerging",
                "label": "Container Merging",
                "repeatable": False,
                "class_path": "MuonAnalysisAlgorithms.MuonAnalysisConfig.MuonContainerMergingConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "PtEtaSelection",
                "label": "pT/η Selection",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PtEtaSelectionBlock",
                "is_function": False,
                "sub_blocks": [],
            },
        ],
    },
    {
        "name": "Photons",
        "label": "Photons",
        "group": "Objects",
        "repeatable": True,
        "class_path": "EgammaAnalysisAlgorithms.PhotonAnalysisConfig.PhotonCalibrationConfig",
        "is_function": False,
        "sub_blocks": [
            {
                "name": "WorkingPoint",
                "label": "Working Point",
                "repeatable": True,
                "class_path": "EgammaAnalysisAlgorithms.PhotonAnalysisConfig.PhotonWorkingPointSelectionConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "PtEtaSelection",
                "label": "pT/η Selection",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PtEtaSelectionBlock",
                "is_function": False,
                "sub_blocks": [],
            },
        ],
    },
    {
        "name": "TauJets",
        "label": "Tau Jets",
        "group": "Objects",
        "repeatable": True,
        "class_path": "TauAnalysisAlgorithms.TauAnalysisConfig.TauCalibrationConfig",
        "is_function": False,
        "sub_blocks": [
            {
                "name": "WorkingPoint",
                "label": "Working Point",
                "repeatable": True,
                "class_path": "TauAnalysisAlgorithms.TauAnalysisConfig.TauWorkingPointSelectionConfig",
                "is_function": False,
                "sub_blocks": [],
            },
            {
                "name": "PtEtaSelection",
                "label": "pT/η Selection",
                "repeatable": False,
                "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PtEtaSelectionBlock",
                "is_function": False,
                "sub_blocks": [],
            },
        ],
    },
    {
        "name": "MissingET",
        "label": "Missing ET",
        "group": "Objects",
        "repeatable": True,
        "class_path": "MetAnalysisAlgorithms.MetAnalysisConfig.MetAnalysisConfig",
        "is_function": False,
        "sub_blocks": [],
    },
    # ── Selection ────────────────────────────────────────────────────────────
    {
        "name": "OverlapRemoval",
        "label": "Overlap Removal",
        "group": "Selection",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.OverlapAnalysisConfig.OverlapAnalysisConfig",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "EventSelection",
        "label": "Event Selection",
        "group": "Selection",
        "repeatable": False,  # selectionCutsDict handles all regions internally
        "class_path": "EventSelectionAlgorithms.EventSelectionConfig.makeMultipleEventSelectionConfigs",
        "is_function": True,
        "sub_blocks": [],
    },
    {
        "name": "EventCutFlow",
        "label": "Event Cut Flow",
        "group": "Selection",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.EventCutFlowBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "ObjectCutFlow",
        "label": "Object Cut Flow",
        "group": "Selection",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.ObjectCutFlowBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    # ── Output ───────────────────────────────────────────────────────────────
    {
        "name": "Thinning",
        "label": "Output Thinning",
        "group": "Output",
        "repeatable": True,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.OutputThinningBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "PerEventSF",
        "label": "Per-Event Scale Factors",
        "group": "Output",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.AsgAnalysisConfig.PerEventSFBlock",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "Output",
        "label": "Output (Ntupling)",
        "group": "Output",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.OutputAnalysisConfig.OutputAnalysisConfig",
        "is_function": False,
        "sub_blocks": [],
    },
    {
        "name": "PrintConfiguration",
        "label": "Print Configuration",
        "group": "Output",
        "repeatable": False,
        "class_path": "AsgAnalysisAlgorithms.PrintToolConfigAlgConfig.PrintToolConfigAlgBlock",
        "is_function": False,
        "sub_blocks": [],
    },
]
