import { describe, it, expect } from 'vitest'
import {
  stripDeprecated, splitCutLines, joinCutLines, parseCutLine, serializeCutLine,
  defaultArgs, keywordNames, specForms, newDraft, draftFromParsed, withForm,
  draftToLine, missingArgs,
} from '../utils/eventSelection.js'
import { KEYWORDS, PARSED, REJECTED } from './fixtures/keywordSpecs.js'

describe('deprecated keywords and line splitting', () => {
  it('drops the lines upstream marks deprecated', () => {
    expect(stripDeprecated('EL_N 25000 >= 1\nSAVE\n', KEYWORDS))
      .toEqual({ text: 'EL_N 25000 >= 1\n', dropped: ['SAVE'] })
    expect(stripDeprecated('EL_N 25000 >= 1', KEYWORDS).dropped).toEqual([])
  })

  it('falls back to SAVE when the release exposes no spec', () => {
    expect(stripDeprecated('OS\nSAVE', null)).toEqual({ text: 'OS', dropped: ['SAVE'] })
  })

  it('never offers a deprecated keyword when adding a cut', () => {
    expect(keywordNames(KEYWORDS)).not.toContain('SAVE')
    expect(keywordNames(KEYWORDS, { includeDeprecated: true })).toContain('SAVE')
    expect(keywordNames(KEYWORDS).length).toBe(Object.keys(KEYWORDS).length - 1)
  })

  it('splits and joins', () => {
    const lines = splitCutLines('  EL_N 25000 >= 1 \n\n# c\nOS')
    expect(lines.map(l => l.raw)).toEqual(['EL_N 25000 >= 1', '# c', 'OS'])
    expect(new Set(lines.map(l => l.id)).size).toBe(3)
    expect(joinCutLines(lines)).toBe('EL_N 25000 >= 1\n# c\nOS')
  })
})

describe('parity with Athena', () => {
  // PARSED/REJECTED are generated by running the real
  // EventSelectionConfig.parseArgs (AB 25.2.110) over these lines.
  it.each(PARSED)('parses $line exactly like EventSelectionConfig', ({ line, keyword, args }) => {
    const p = parseCutLine(line, KEYWORDS)
    expect(p.keyword).toBe(keyword)
    expect(p.error).toBeNull()
    expect(p.args).toEqual(args)
  })

  it.each(REJECTED)('rejects %s, as Athena does', (line) => {
    expect(parseCutLine(line, KEYWORDS).args).toBeNull()
  })

  it('round-trips every accepted line back to its original text', () => {
    for (const { line } of PARSED) {
      const p = parseCutLine(line, KEYWORDS)
      expect(serializeCutLine(p.keyword, p.args, KEYWORDS, p.form)).toBe(line)
    }
  })

  it('covers every keyword the release declares', () => {
    const seen = new Set(PARSED.map(c => c.keyword))
    expect([...Object.keys(KEYWORDS)].filter(kw => !seen.has(kw))).toEqual([])
  })
})

describe('parseCutLine', () => {
  it('is opaque without a keyword spec', () => {
    const p = parseCutLine('EL_N 25000 >= 1', null)
    expect(p).toMatchObject({ keyword: 'EL_N', args: null, spec: null, error: null })
  })

  it('reports an unknown keyword', () => {
    expect(parseCutLine('BOGUS 1', KEYWORDS).error).toBe("Unknown keyword 'BOGUS'")
  })

  it('reports a line that fits no form', () => {
    const bad = parseCutLine('EL_N 1', KEYWORDS)
    expect(bad.args).toBeNull()
    expect(bad.error).toMatch(/EL_N does not accept 1 argument$/)
    expect(parseCutLine('RUN_NUMBER >= 1 2', KEYWORDS).error).toMatch(/3 arguments/)
  })

  it('ignores blanks and comments', () => {
    expect(parseCutLine('# hi', KEYWORDS).keyword).toBeNull()
    expect(parseCutLine('   ', KEYWORDS).keyword).toBeNull()
  })

  it('reads flags by name wherever they appear, as booleans', () => {
    expect(parseCutLine('OS mu', KEYWORDS).args).toEqual({ el: false, mu: true, tau: false })
    expect(parseCutLine('OS tau el', KEYWORDS).args).toEqual({ el: true, mu: false, tau: true })
    expect(parseCutLine('LJETMASSWINDOW_N veto 50000 100000 >= 1', KEYWORDS).args)
      .toEqual({ sel: '', lowMass: '50000', highMass: '100000', sign: '>=', count: '1', veto: true })
  })

  it('uses the pattern to tell two optionals apart', () => {
    // JET_N_BTAG: `sel` is a plain word, `btag` is 'tagger:WP'.
    expect(parseCutLine('JET_N_BTAG GN2v01:FixedCutBEff_77 >= 2', KEYWORDS).args)
      .toEqual({ sel: '', btag: 'GN2v01:FixedCutBEff_77', sign: '>=', count: '2' })
    expect(parseCutLine('JET_N_BTAG tight >= 2', KEYWORDS).args)
      .toEqual({ sel: 'tight', btag: '', sign: '>=', count: '2' })
  })

  it('picks the matching form and reports which one matched', () => {
    const one = parseCutLine('SUM_EL_N_MU_N 25000 >= 2', KEYWORDS)
    expect(one.args).toEqual({ ptmin: '25000', sign: '>=', count: '2' })
    expect(one.form.map(a => a.name)).toEqual(['ptmin', 'sign', 'count'])

    const two = parseCutLine('SUM_EL_N_MU_N 25000 30000 >= 2', KEYWORDS)
    expect(two.args).toEqual({ ptEl: '25000', ptMu: '30000', sign: '>=', count: '2' })
    expect(two.form.map(a => a.name)).toEqual(['ptEl', 'ptMu', 'sign', 'count'])
  })

  it('keeps free text in one piece', () => {
    expect(parseCutLine('EXPR dR(jet[0],jet[1]) > 0.4', KEYWORDS).args)
      .toEqual({ text: 'dR(jet[0],jet[1]) > 0.4' })
  })
})

describe('serializeCutLine and defaultArgs', () => {
  it('omits empty optionals and writes flags as their name', () => {
    expect(serializeCutLine('EL_N', { sel: '', ptmin: '25000', sign: '>=', count: '1' }, KEYWORDS))
      .toBe('EL_N 25000 >= 1')
    expect(serializeCutLine('OS', { el: false, mu: true, tau: false }, KEYWORDS)).toBe('OS mu')
    expect(serializeCutLine('OS', { el: false, mu: false, tau: false }, KEYWORDS)).toBe('OS')
  })

  it('serializes against the form it is given', () => {
    const form = specForms(KEYWORDS.SUM_EL_N_MU_N)[1]
    expect(serializeCutLine('SUM_EL_N_MU_N', { ptEl: '25000', ptMu: '30000', sign: '>=', count: '2' }, KEYWORDS, form))
      .toBe('SUM_EL_N_MU_N 25000 30000 >= 2')
  })

  it('gives empty values, >= for signs and false for flags', () => {
    expect(defaultArgs('EL_N', KEYWORDS)).toEqual({ sel: '', ptmin: '', sign: '>=', count: '' })
    expect(defaultArgs('OS', KEYWORDS)).toEqual({ el: false, mu: false, tau: false })
    expect(defaultArgs('EXPR', KEYWORDS)).toEqual({ text: '' })
    expect(defaultArgs('NOPE', KEYWORDS)).toBeNull()
  })

  it('a freshly added cut of every keyword parses back', () => {
    for (const kw of keywordNames(KEYWORDS)) {
      const line = serializeCutLine(kw, defaultArgs(kw, KEYWORDS), KEYWORDS)
      expect(parseCutLine(line, KEYWORDS).keyword).toBe(kw)
    }
  })
})


describe('drafts (a row being edited)', () => {
  // Regression: adding a keyword used to hand the user a bare text box.  The
  // row was re-derived from its text, and an empty argument serialises to
  // nothing, so a fresh EL_N became "EL_N  >=" — which parses as one argument,
  // matches no form, and falls back to raw text with no idea what to type.
  it('a fresh keyword is structured even though its line is not parsable', () => {
    for (const kw of keywordNames(KEYWORDS)) {
      const draft = newDraft(kw, KEYWORDS)
      expect(draft, kw).not.toBeNull()
      expect(draft.keyword, kw).toBe(kw)
      expect(draft.args, kw).toEqual(defaultArgs(kw, KEYWORDS))
      // the draft survives whether or not its own text parses back
      expect(draft.form === null || Array.isArray(draft.form), kw).toBe(true)
    }
  })

  it('keeps the arguments a half-finished line cannot carry', () => {
    const draft = newDraft('EL_N', KEYWORDS)
    expect(draftToLine(draft, KEYWORDS)).toBe('EL_N >=')          // lossy on purpose
    expect(parseCutLine(draftToLine(draft, KEYWORDS), KEYWORDS).args).toBeNull()
    // …but the draft still knows every argument, which is what gets rendered
    expect(Object.keys(draft.args)).toEqual(['sel', 'ptmin', 'sign', 'count'])
    expect(missingArgs(draft.form, draft.args)).toEqual(['ptmin', 'count'])
  })

  it('fills in as the user types, and is complete when nothing is missing', () => {
    let draft = newDraft('EL_N', KEYWORDS)
    draft = { ...draft, args: { ...draft.args, ptmin: '25000' } }
    expect(missingArgs(draft.form, draft.args)).toEqual(['count'])
    draft = { ...draft, args: { ...draft.args, count: '1' } }
    expect(missingArgs(draft.form, draft.args)).toEqual([])
    const line = draftToLine(draft, KEYWORDS)
    expect(line).toBe('EL_N 25000 >= 1')
    expect(parseCutLine(line, KEYWORDS).args).toEqual(draft.args)
  })

  it('values never move between fields while typing', () => {
    // Filling `count` before `ptmin` used to re-parse ">=" into ptmin.
    let draft = newDraft('EL_N', KEYWORDS)
    draft = { ...draft, args: { ...draft.args, count: '2' } }
    expect(draft.args.ptmin).toBe('')
    expect(draft.args.sign).toBe('>=')
    expect(draft.args.count).toBe('2')
  })

  it('an optional argument left empty is not missing', () => {
    const draft = newDraft('GLOBALTRIGMATCH', KEYWORDS)
    expect(missingArgs(draft.form, draft.args)).toEqual([])
    expect(draftToLine(draft, KEYWORDS)).toBe('GLOBALTRIGMATCH')
  })

  it('flags and signs are never missing', () => {
    expect(missingArgs(specForms(KEYWORDS.OS)[0], newDraft('OS', KEYWORDS).args)).toEqual([])
    const mllw = newDraft('MLLWINDOW', KEYWORDS)
    expect(missingArgs(mllw.form, mllw.args)).toEqual(['lowMLL', 'highMLL'])   // not `veto`
  })

  it('free-text keywords draft their text', () => {
    const draft = newDraft('EXPR', KEYWORDS)
    expect(draft.form).toBeNull()
    expect(draft.args).toEqual({ text: '' })
    expect(draftToLine({ ...draft, args: { text: 'dR(el[0],jet[0]) > 0.4' } }, KEYWORDS))
      .toBe('EXPR dR(el[0],jet[0]) > 0.4')
  })

  it('an existing line keeps its values when it becomes a draft', () => {
    const parsed = parseCutLine('JET_N_BTAG tight GN2v01:FixedCutBEff_77 >= 2', KEYWORDS)
    const draft = draftFromParsed(parsed)
    expect(draft.keyword).toBe('JET_N_BTAG')
    expect(draft.args).toEqual(parsed.args)
    expect(draftToLine(draft, KEYWORDS)).toBe('JET_N_BTAG tight GN2v01:FixedCutBEff_77 >= 2')
  })

  it('a line that does not parse yields no draft, so it stays raw text', () => {
    expect(draftFromParsed(parseCutLine('EL_N 1', KEYWORDS))).toBeNull()
    expect(draftFromParsed(parseCutLine('BOGUS', KEYWORDS))).toBeNull()
    expect(draftFromParsed(parseCutLine('# comment', KEYWORDS))).toBeNull()
  })

  it('switching form keeps the values whose names survive', () => {
    const forms = specForms(KEYWORDS.SUM_EL_N_MU_N)
    let draft = newDraft('SUM_EL_N_MU_N', KEYWORDS)
    draft = { ...draft, args: { ...draft.args, ptmin: '25000', sign: '>', count: '2' } }

    const two = withForm(draft, forms[1], KEYWORDS)
    expect(Object.keys(two.args)).toEqual(['ptEl', 'ptMu', 'sign', 'count'])
    expect(two.args.sign).toBe('>')        // kept
    expect(two.args.count).toBe('2')       // kept
    expect(two.args.ptEl).toBe('')         // new argument, blank
    expect(missingArgs(two.form, two.args)).toEqual(['ptEl', 'ptMu'])

    const back = withForm(two, forms[0], KEYWORDS)
    expect(Object.keys(back.args)).toEqual(['ptmin', 'sign', 'count'])
    expect(back.args.count).toBe('2')
  })

  it('every form of every keyword can be drafted and serialised', () => {
    for (const kw of keywordNames(KEYWORDS)) {
      if (KEYWORDS[kw].freeText) {
        // free text has no argument form at all
        expect(newDraft(kw, KEYWORDS).form, kw).toBeNull()
        continue
      }
      for (const form of specForms(KEYWORDS[kw])) {
        const draft = newDraft(kw, KEYWORDS, form)
        expect(draft.form, kw).toBe(form)
        expect(draftToLine(draft, KEYWORDS).split(/\s+/)[0], kw).toBe(kw)
      }
    }
  })

  it('newDraft refuses an unknown keyword', () => {
    expect(newDraft('NOPE', KEYWORDS)).toBeNull()
    expect(draftToLine(null, KEYWORDS)).toBe('')
    expect(withForm(null, [], KEYWORDS)).toBeNull()
    expect(missingArgs(null, null)).toEqual([])
  })
})
