import { describe, it, expect } from 'vitest'
import {
  stripDeprecated, splitCutLines, joinCutLines, parseCutLine, serializeCutLine,
  defaultArgs, keywordNames, specForms,
} from '../utils/eventSelection.js'
import { KEYWORDS, PARSED, REJECTED } from './fixtures/keywordSpecs.js'

describe('deprecated keywords and line splitting', () => {
  it('drops the lines upstream marks deprecated', () => {
    expect(stripDeprecated('EL_N 25000 >= 1\nSAVE\n', KEYWORDS))
      .toEqual({ text: 'EL_N 25000 >= 1\n', dropped: ['SAVE'] })
    expect(stripDeprecated('EL_N 25000 >= 1', KEYWORDS).dropped).toEqual([])
  })

  it('falls back to SAVE when the release exposes no spec', () => {
    expect(stripDeprecated('OS\nSAVE', null)).toEqual({ text: 'OS', dropped: ['SAVE'] })
  })

  it('never offers a deprecated keyword when adding a cut', () => {
    expect(keywordNames(KEYWORDS)).not.toContain('SAVE')
    expect(keywordNames(KEYWORDS, { includeDeprecated: true })).toContain('SAVE')
    expect(keywordNames(KEYWORDS).length).toBe(Object.keys(KEYWORDS).length - 1)
  })

  it('splits and joins', () => {
    const lines = splitCutLines('  EL_N 25000 >= 1 \n\n# c\nOS')
    expect(lines.map(l => l.raw)).toEqual(['EL_N 25000 >= 1', '# c', 'OS'])
    expect(new Set(lines.map(l => l.id)).size).toBe(3)
    expect(joinCutLines(lines)).toBe('EL_N 25000 >= 1\n# c\nOS')
  })
})

describe('parity with Athena', () => {
  // PARSED/REJECTED are generated by running the real
  // EventSelectionConfig.parseArgs (AB 25.2.110) over these lines.
  it.each(PARSED)('parses $line exactly like EventSelectionConfig', ({ line, keyword, args }) => {
    const p = parseCutLine(line, KEYWORDS)
    expect(p.keyword).toBe(keyword)
    expect(p.error).toBeNull()
    expect(p.args).toEqual(args)
  })

  it.each(REJECTED)('rejects %s, as Athena does', (line) => {
    expect(parseCutLine(line, KEYWORDS).args).toBeNull()
  })

  it('round-trips every accepted line back to its original text', () => {
    for (const { line } of PARSED) {
      const p = parseCutLine(line, KEYWORDS)
      expect(serializeCutLine(p.keyword, p.args, KEYWORDS, p.form)).toBe(line)
    }
  })

  it('covers every keyword the release declares', () => {
    const seen = new Set(PARSED.map(c => c.keyword))
    expect([...Object.keys(KEYWORDS)].filter(kw => !seen.has(kw))).toEqual([])
  })
})

describe('parseCutLine', () => {
  it('is opaque without a keyword spec', () => {
    const p = parseCutLine('EL_N 25000 >= 1', null)
    expect(p).toMatchObject({ keyword: 'EL_N', args: null, spec: null, error: null })
  })

  it('reports an unknown keyword', () => {
    expect(parseCutLine('BOGUS 1', KEYWORDS).error).toBe("Unknown keyword 'BOGUS'")
  })

  it('reports a line that fits no form', () => {
    const bad = parseCutLine('EL_N 1', KEYWORDS)
    expect(bad.args).toBeNull()
    expect(bad.error).toMatch(/EL_N does not accept 1 argument$/)
    expect(parseCutLine('RUN_NUMBER >= 1 2', KEYWORDS).error).toMatch(/3 arguments/)
  })

  it('ignores blanks and comments', () => {
    expect(parseCutLine('# hi', KEYWORDS).keyword).toBeNull()
    expect(parseCutLine('   ', KEYWORDS).keyword).toBeNull()
  })

  it('reads flags by name wherever they appear, as booleans', () => {
    expect(parseCutLine('OS mu', KEYWORDS).args).toEqual({ el: false, mu: true, tau: false })
    expect(parseCutLine('OS tau el', KEYWORDS).args).toEqual({ el: true, mu: false, tau: true })
    expect(parseCutLine('LJETMASSWINDOW_N veto 50000 100000 >= 1', KEYWORDS).args)
      .toEqual({ sel: '', lowMass: '50000', highMass: '100000', sign: '>=', count: '1', veto: true })
  })

  it('uses the pattern to tell two optionals apart', () => {
    // JET_N_BTAG: `sel` is a plain word, `btag` is 'tagger:WP'.
    expect(parseCutLine('JET_N_BTAG GN2v01:FixedCutBEff_77 >= 2', KEYWORDS).args)
      .toEqual({ sel: '', btag: 'GN2v01:FixedCutBEff_77', sign: '>=', count: '2' })
    expect(parseCutLine('JET_N_BTAG tight >= 2', KEYWORDS).args)
      .toEqual({ sel: 'tight', btag: '', sign: '>=', count: '2' })
  })

  it('picks the matching form and reports which one matched', () => {
    const one = parseCutLine('SUM_EL_N_MU_N 25000 >= 2', KEYWORDS)
    expect(one.args).toEqual({ ptmin: '25000', sign: '>=', count: '2' })
    expect(one.form.map(a => a.name)).toEqual(['ptmin', 'sign', 'count'])

    const two = parseCutLine('SUM_EL_N_MU_N 25000 30000 >= 2', KEYWORDS)
    expect(two.args).toEqual({ ptEl: '25000', ptMu: '30000', sign: '>=', count: '2' })
    expect(two.form.map(a => a.name)).toEqual(['ptEl', 'ptMu', 'sign', 'count'])
  })

  it('keeps free text in one piece', () => {
    expect(parseCutLine('EXPR dR(jet[0],jet[1]) > 0.4', KEYWORDS).args)
      .toEqual({ text: 'dR(jet[0],jet[1]) > 0.4' })
  })
})

describe('serializeCutLine and defaultArgs', () => {
  it('omits empty optionals and writes flags as their name', () => {
    expect(serializeCutLine('EL_N', { sel: '', ptmin: '25000', sign: '>=', count: '1' }, KEYWORDS))
      .toBe('EL_N 25000 >= 1')
    expect(serializeCutLine('OS', { el: false, mu: true, tau: false }, KEYWORDS)).toBe('OS mu')
    expect(serializeCutLine('OS', { el: false, mu: false, tau: false }, KEYWORDS)).toBe('OS')
  })

  it('serializes against the form it is given', () => {
    const form = specForms(KEYWORDS.SUM_EL_N_MU_N)[1]
    expect(serializeCutLine('SUM_EL_N_MU_N', { ptEl: '25000', ptMu: '30000', sign: '>=', count: '2' }, KEYWORDS, form))
      .toBe('SUM_EL_N_MU_N 25000 30000 >= 2')
  })

  it('gives empty values, >= for signs and false for flags', () => {
    expect(defaultArgs('EL_N', KEYWORDS)).toEqual({ sel: '', ptmin: '', sign: '>=', count: '' })
    expect(defaultArgs('OS', KEYWORDS)).toEqual({ el: false, mu: false, tau: false })
    expect(defaultArgs('EXPR', KEYWORDS)).toEqual({ text: '' })
    expect(defaultArgs('NOPE', KEYWORDS)).toBeNull()
  })

  it('a freshly added cut of every keyword parses back', () => {
    for (const kw of keywordNames(KEYWORDS)) {
      const line = serializeCutLine(kw, defaultArgs(kw, KEYWORDS), KEYWORDS)
      expect(parseCutLine(line, KEYWORDS).keyword).toBe(kw)
    }
  })
})
