name: Build and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'VERSION'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install oc CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
 
      - name: OC login
        run: |
          oc login --server=https://api.paas.okd.cern.ch \
            --token="${{ secrets.OC_TOKEN }}" \
            --insecure-skip-tls-verify

      - name: Deploy
        env:
          CERN_TOKEN: ${{ secrets.CERN_TOKEN }}
          DOCKER_BUILDKIT: "1"        # required for --secret in docker build
        run: bash deploy.sh v2.24.0
